# backend/main.py

from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Dict, Any, Optional
import os
from dotenv import load_dotenv # Used to load .env file

import google.generativeai as genai

# Load environment variables from .env file
load_dotenv()

app = FastAPI(
    title="Gemini Excel Add-in Proxy",
    description="Proxies requests from Excel Add-in to Google Gemini API securely."
)

# --- CORS Configuration ---pip install fastapi "uvicorn[standard]" python-dotenv google-generativeai
# IMPORTANT: These origins must match where your Excel Add-in is running.
# For local testing, your Excel Add-in runs on HTTPS localhost:3000 (usually).
# For deployed version (GitHub Pages), it would be your GitHub Pages URL.
origins = [
    "https://localhost:3000",       # Your Excel Add-in's local development URL (HTTPS)
    "http://localhost:3000",        # Sometimes needed for local dev (HTTP)
    "https://localhost",            # Generic localhost often used by Office dev tools
    "http://localhost",
    # When deployed to GitHub Pages, you'd add:
    "https://soumya-dass.github.io",
    "https://soumya-dass.github.io/excel-chatbot-addin",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],  # Allows all methods (GET, POST, etc.)
    allow_headers=["*"],  # Allows all headers
)

# --- Gemini API Configuration ---
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY") # Get API key from environment variable
if not GEMINI_API_KEY:
    raise ValueError("GEMINI_API_KEY not found in environment variables. Please set it in your .env file.")

genai.configure(api_key=GEMINI_API_KEY)
# Using the same model as specified in your aiService.js
GEMINI_MODEL_NAME = 'gemini-2.5-flash'
model = genai.GenerativeModel(GEMINI_MODEL_NAME)

# --- Pydantic Models for Request Body ---
# This defines the structure of the JSON data your frontend will send.
class ClientMessage(BaseModel):
    role: str # "user" or "assistant" from client
    content: str

class AskGeminiRequest(BaseModel):
    # This will be the full contextual prompt string generated by the client's aiService
    currentPrompt: str
    # The conversation history *before* the current turn
    conversationHistory: List[ClientMessage] = []

# --- API Endpoint ---
@app.post("/ask-gemini")
async def ask_gemini_proxy(request_data: AskGeminiRequest):
    """
    Proxies requests from the Excel Add-in to the Google Gemini API securely.
    The client generates the contextual prompt string and sends it, along with
    the previous conversation history for context.
    """
    try:
        # Format the client's history for Gemini API's expected format
        formatted_history = []
        for msg in request_data.conversationHistory:
            # Map client's 'assistant' role to Gemini's 'model' role
            gemini_role = "user" if msg.role == "user" else "model"
            formatted_history.append({"role": gemini_role, "parts": [{"text": msg.content}]})

        # Start a new chat session with the provided history.
        # This makes the backend effectively stateless for each request, as history
        # is always passed from the client, ensuring correct context.
        chat_session = model.start_chat(history=formatted_history)

        # Send the current prompt (which includes user question + worksheet context)
        gemini_response = await chat_session.send_message_async(request_data.currentPrompt)

        # Extract the AI's text response
        ai_response_text = gemini_response.text

        # Return the AI response in a JSON format that your frontend expects
        return {"aiResponse": ai_response_text}

    except genai.types.BlockedPromptException as e:
        # Handle cases where Gemini blocks a prompt (e.g., for safety)
        print(f"Gemini API blocked prompt: {e.response.prompt_feedback.block_reason}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Gemini API blocked prompt: {e.response.prompt_feedback.block_reason}. Please rephrase your question."
        )
    except Exception as e:
        # Catch any other unexpected errors during the process
        print(f"Error calling Gemini API: {e}") # Log error to console for debugging
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An internal error occurred while getting AI response. Please try again. ({str(e)})"
        )

# --- Basic Root Endpoint (Optional, for health check) ---
# You can visit http://localhost:8000/ in your browser to check if the server is running.
@app.get("/")
async def root():
    return {"message": "Gemini Excel Add-in Proxy is running!"}